config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # get '/articles', to: 'articles#index'
  # get '/articles/:id', to: 'articles#show'

  resources :articles#, only: %i[index show new create edit update delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :fetch_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    return redirect_to @article if @article.save

    render :new
  end

  def show; end

  def edit; end

  def update
    return redirect_to @article if @article.update(article_params)

    render :edit
  end

  def destroy
    @article.destroy
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def fetch_article
    @article = Article.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<p>
  <%= article.title %>
  <br>
  <%= article.description.truncate(5) %>
  <br>
  <%= link_to 'detalhes', article %> | 
  <%= link_to 'editar', edit_article_path(article) %> | 
  <%= link_to 'apagar', article_path(article), data: {turbo_method: :delete } %> 
</p>

app/views/articles/_form.html.erb
<%= form_with model: @article, data: { turbo: false } do |f| %>
  <p>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h2>Edição de Artigo</h2>

<%= render 'shared/errors', object: @article %>

<%= render 'form' %>

app/views/articles/index.html.erb
<h2>Artigos</h2>

<p>
  <%= link_to 'Novo', new_article_path %>
</p>

<%= render @articles %>

app/views/articles/new.html.erb
<h2>Novo Artigo</h2>

<%= render 'shared/errors', object: @article %>

<%= render 'form' %>

app/views/articles/show.html.erb
<%= render @article %>

app/views/home/index.html.erb
<h2>Home</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <p>
      <%= message %>
    </p>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<h2>App</h2>

<nav>
  <%= link_to 'Home', root_path %>
  <%= link_to 'Articles', articles_path %>
</nav>

<hr>